### ISSUE TITLE
The injector crashes the game directly, and the releases are not seen here.

### ISSUE THREAD

**Issue by lauwalker** [Aquatic-Labs/Umbra-Menu-Injector#4]
As written in the title, the injector auto updates to v99.999.999 and crashes the game. I think this may be due to a recent update in the game. 
One other thing is none of the releases are seen in this thread. I think they may need to be updated here as well.

**Comment by NeonixRIT** [comment]
This is due to the recent migration to Aquatic Labs. Make sure you have the latest version of the injector installed.

**Comment by lauwalker** [comment]
I cannot find the latest version of the injector on this thread. Is it in the releases section?

**Comment by NeonixRIT** [comment]
https://github.com/Aquatic-Labs/Umbra-Menu-Injector/releases/latest/

**Comment by lauwalker** [comment]
Ty!
